apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: smartinventory
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1,smartinventory-service"
  DATABASE_URL: "mysql://root:root@mysql-service:3306/smartinventory2"
  REDIS_URL: "redis://redis-service:6379/0"
  SECRET_KEY: "production-secret-key-change-me"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: smartinventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: smartinventory:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: web-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: smartinventory-service
  namespace: smartinventory
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartinventory-ingress
  namespace: smartinventory
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: smartinventory.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartinventory-service
            port:
              number: 80